/*
 * 《逆命蛊途》万蛊录数据 · gu_catalog.js
 * category="gu"  —— 已实装为战斗蛊牌(以游戏 CARD_LIBRARY 真实数据为准)，cardKey 对应卡键名、用于解锁判定。
 * category="eco" —— gu 文件夹有立绘、但游戏内暂未实装为战斗蛊牌的“生态蛊”，无 cardKey、不参与战斗，恒显示并标注“暂未实装为战斗蛊牌”。
 * 名称一律以游戏真实卡牌名为准；按“蛊虫本体”去重(每只一条)。缺图条目 image 留空，详情页回退暗色单字立绘框。
 * gameplayEffect 取自真实卡牌 effect(去标签纯文本)，不杜撰不存在的战斗效果。
 */
window.GU_CATALOG = [
  /* ===== 战斗蛊(已实装) ===== */
  {
    id: "gu_moonblade", category: "gu", cardKey: "moonBlade",
    name: "月刃蛊", alias: "弦月之牙", rarity: "凡蛊", faction: "护身", type: "攻击", stage: "成蛊·锋形",
    descriptionShort: "凝月华为刃的入门攻蛊。",
    descriptionLore: "残篇载：山月将满之夜，取蛊于古剑铭槽之内，其背生一弯白纹，状若初弦。养之七日不喂血食，唯以月光淬体，则薄翅渐硬如刃。蛊师一念既动，月刃应声而出，断敌而不沾尘。「月满则缺，刃出则收」——此乃蛊修最初学得的杀机。",
    habitat: "栖于荒祠断剑、月照所及的金石缝隙。", feeding: "不食血肉，唯饮月华与寒露。", temperament: "性冷而驯，认主极早，是蛊修第一口养器。",
    evolution: "久养可向「异刃蛊」蜕形，锋更厉而性更躁。", synergy: "得「酒虫」醉气加持时，一刃可断两命。", counteredBy: "畏厚甲与无月之夜，光弱则刃钝。",
    dropsFrom: "命途初阶、无名逆命者起手蛊囊。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "对敌人造成 6 点伤害。", image: "assets/codex/gu/moonblade-gu.webp",
  },
  {
    id: "gu_ironskin", category: "gu", cardKey: "ironSkin",
    name: "铁皮蛊", alias: "覆甲虫", rarity: "凡蛊", faction: "护身", type: "防御", stage: "成蛊·甲形",
    descriptionShort: "伏于体表化甲御伤的护蛊。",
    descriptionLore: "秘录残页：此蛊生于矿脉锈水之中，壳坚而色暗，似铁非铁。蛊师以气引之伏于皮下，临敌则千甲齐张、层层相叠，覆体如鳞。古谚云「铁皮一展，刀斧三分」，言其虽贱却最是耐磨的命门屏障。",
    habitat: "潜居废矿、锈水、铁器埋骨之地。", feeding: "啃食铁锈与金石之屑，越坚越喜。", temperament: "迟钝而忠，宁碎不退，护主至死。",
    evolution: "可炼为「异甲蛊」，甲更厚而反噬其主。", synergy: "与「残壳蛊」「蜕壳蛊」叠甲成阵，伤而愈坚。", counteredBy: "惧蚀甲之毒与破甲之牙，甲破则形溃。",
    dropsFrom: "命途初阶、各蛊修起手蛊囊。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 7 点防御。", image: "assets/codex/gu/iron-shell-gu.webp",
  },
  {
    id: "gu_wineworm", category: "gu", cardKey: "wineWorm",
    name: "酒虫", alias: "醉魇", rarity: "灵蛊", faction: "控场", type: "辅助", stage: "灵蛊·酿形",
    descriptionShort: "吐醉气令下一击翻倍的辅蛊。",
    descriptionLore: "古卷云：酒虫不入杀阵，却最坏分寸。其腹常蕴一囊浊酿，遇敌则吐雾成醉。中者神驰目眩，挥拳如缚、避刃迟半息，故继之而来的一蛊，伤可加倍。蛊师戏称：「先敬一盏，再送一刀。」",
    habitat: "藏于酒窖陈瓮、败果腐浆的甜腥之处。", feeding: "饮陈酿、噬醉气，越烈越肥。", temperament: "贪而懒，非诱以酒香不肯出囊。",
    evolution: "醉性入命，可化「醉命虫」，醉中亦能窃命。", synergy: "醉气加持任意攻蛊，与「月刃蛊」一刃断两命。", counteredBy: "对无神识、不饮不醉之傀儡尸物近乎无用。",
    dropsFrom: "命途辅助蛊奖励、燃命流起手蛊囊。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "下一张攻击蛊的伤害翻倍。", image: "assets/codex/gu/wineworm-gu.webp",
  },
  {
    id: "gu_bloodblade", category: "gu", cardKey: "bloodBlade",
    name: "血刃蛊", alias: "饮煞牙", rarity: "异蛊", faction: "血道", type: "攻击", stage: "异蛊·煞形",
    descriptionShort: "割己血换爆发、积煞愈烈的血蛊。",
    descriptionLore: "血道残卷：此蛊嗜主血如蜜，每出必先啮主一口，借三分热血淬其牙锋。血出愈多，煞气愈凝，凝者附于蛊背成赤纹，谓之「血煞」。煞深则一刃裂石。绛妄一脉以命饲蛊、以煞换力，正是从这一口血起。",
    habitat: "盘踞古战场尸血浸透的黑土深处。", feeding: "唯饮主血与战场残煞，不食他物。", temperament: "狂而贪，喂之愈急、索之愈狠。",
    evolution: "煞积成形可蜕「血月蛊」，月圆煞涌。", synergy: "与「噬心蛊」「逆血蛊」结血煞循环，越战越凶。", counteredBy: "惧疗血断煞之术；主血枯则蛊自噬反伤。",
    dropsFrom: "绛妄起手蛊囊、血道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "失去 3 点生命，造成 13 + 当前血煞 点伤害，获得 1 层血煞。", image: "assets/codex/gu/bloodblade-gu.webp",
  },
  {
    id: "gu_greenmiasma", category: "gu", cardKey: "greenMiasma",
    name: "青瘴蛊", alias: "蟒涎瘴", rarity: "灵蛊", faction: "毒道", type: "状态", stage: "灵蛊·瘴形",
    descriptionShort: "吐青瘴叠毒、铺设蚀命之雾的毒蛊。",
    descriptionLore: "毒道秘篇：青瘴本是巨蟒口涎所凝，蛊师收之入囊，养以腐藤瘴气。其不咬不噬，唯吐一缕青烟附敌之身，烟不散则毒不止，层叠愈厚、蚀命愈深。青蟒一脉言：「不必一击致命，只需让它慢慢烂尽。」",
    habitat: "潜伏瘴林深泽、蟒蜕腐藤的湿绿之地。", feeding: "吞腐藤、噬瘴气，喜阴湿恶日光。", temperament: "阴而韧，不争锋而善缠，毒发无声。",
    evolution: "瘴极而变可化「异毒蛊」，一吐九层。", synergy: "与「虫群蛊」「腐瘴蛊」叠毒成阵，毒越深伤越重。", counteredBy: "惧净毒驱瘴之术与速攻爆发，毒未发已先亡。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "施加 4 层毒性。", image: "assets/codex/gu/green-miasma-gu.webp",
  },
  {
    id: "gu_insectswarm", category: "gu", cardKey: "insectSwarm",
    name: "虫群蛊", alias: "万口噬", rarity: "灵蛊", faction: "虫群", type: "攻击", stage: "灵蛊·群形",
    descriptionShort: "驱群虫啮咬、攻伤兼施毒的虫蛊。",
    descriptionLore: "残卷曰：一蛊为母，孵子千百，密如黑雨。临敌则倾囊而出，啮其血肉、注其毒涎，咬处溃烂、烂处复咬。蛊师御之，非以一蛊之力，而以万口之势。「单虫不足惧，万口可拆山」——此虫群之道。",
    habitat: "聚居枯木朽穴、尸骸蚁丘的密暗之所。", feeding: "食血肉腐殍，越腥越聚、越聚越饥。", temperament: "无主见而易裹挟，势成则不可遏。",
    evolution: "群密毒浓可并入「腐瘴蛊」之蚀毒循环。", synergy: "得「青瘴蛊」铺毒在前，群至则毒伤齐爆。", counteredBy: "惧火与范围净毒，一炬可焚千口。",
    dropsFrom: "青蟒流毒道蛊奖励、命途虫群事件。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 4 点伤害，并施加 4 层毒性。", image: "assets/codex/gu/swarm-gu.webp",
  },
  {
    id: "gu_fatethread", category: "gu", cardKey: "fateThread",
    name: "命线蛊", alias: "牵命丝", rarity: "异蛊", faction: "命途", type: "攻击", stage: "异蛊·命形",
    descriptionShort: "借命势加成、势盛则伤增的命蛊。",
    descriptionLore: "逆命残篇：此蛊体内有一缕看不见的细丝，连主之气运。蛊师攻守相替、命势渐积，丝便绷紧；势满则丝如弓弦，一拨之间割开敌命。无名逆命者无天命可恃，唯以这一线之势，自命途夹缝里硬挣出一条生路。",
    habitat: "无定所，唯附于气运纠缠、生死交错之人。", feeding: "不食血肉，唯汲主之「命势」而长。", temperament: "灵而傲，势弱则蛰伏，势盛则锋出。",
    evolution: "势数圆融，可与「定数蛊」共结命势循环。", synergy: "攻守交替积势，与「逆途蛊」相济，势满则命线一击加倍利。", counteredBy: "惧夺势断流之扰，命势一散则丝软无力。",
    dropsFrom: "无名逆命者起手蛊囊、命势流蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 8 点伤害；命势不少于 2 层时额外造成 6 点伤害。", image: "assets/codex/gu/fate-thread-gu.webp",
  },
  {
    id: "gu_burningessence", category: "gu", cardKey: "burningEssence",
    name: "燃元蛊", alias: "焚命引", rarity: "凡蛊", faction: "燃命", type: "辅助", stage: "凡蛊·火形",
    descriptionShort: "焚生命换真元、以命续力的燃蛊。",
    descriptionLore: "残页警语：燃元蛊小如火星，却最是凶险的捷径。它噬主一缕生机，便能在丹田点起一点真元，催动后续诸蛊。用之者快意一时，却不知每一分元气，都是从自己的命数里硬烧出来的。「燃命者，先燃己。」",
    habitat: "蛰伏炉灰余烬、丹鼎裂隙的温热之处。", feeding: "焚主之生机为薪，得元则旺，元尽则寒。", temperament: "急而烈，催之即应，不知节制。",
    evolution: "可炼入「魂燃蛊」，焚命更猛、续力更狠。", synergy: "为真元流起手引擎，与「聚元蛊」相济不竭。", counteredBy: "无外敌可克，唯主之生命为其上限，命薄则自焚。",
    dropsFrom: "燃命流起手蛊囊、命途真元事件。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 1 点真元，但失去 2 点生命。", image: "assets/codex/gu/burning-yuan-gu.webp",
  },
  {
    id: "gu_hearteater", category: "gu", cardKey: "heartEater",
    name: "噬心蛊", alias: "啖心赤蛛", rarity: "异蛊", faction: "血道", type: "攻击", stage: "异蛊·赤形",
    descriptionShort: "血煞愈厚、一击啖心的重攻血蛊。",
    descriptionLore: "血道残卷：此蛊形如赤蛛，多须如根，专寻心血最盛之处下口。血煞未凝时，它只是缓缓啃咬；煞气一足，便如开闸，整颗心连血带念一并啖尽。绛妄门下传言，养此蛊者夜里常听见自己的心跳被另一物数着。",
    habitat: "盘踞血祭遗坛、尸心未冷的暗祠。", feeding: "唯啖心血与凝结的血煞。", temperament: "贪忍而耐，越是养得久越是难填。",
    evolution: "煞极而变，可与「血月蛊」共振，月圆则啖。", synergy: "与「血刃蛊」「血祭蛊」叠煞，煞满二层则一口翻倍。", counteredBy: "煞气一断便绵软无力；惧疗血与净煞之术。",
    dropsFrom: "通用进阶牌池(战后奖励)、血道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 12 点伤害；血煞不少于 2 层时改为 20。", image: "assets/codex/gu/heart-devour-gu.webp",
  },
  {
    id: "gu_bloodreversal", category: "gu", cardKey: "bloodReversal",
    name: "逆血蛊", alias: "倒煞牙", rarity: "异蛊", faction: "血道", type: "攻击", stage: "异蛊·逆形",
    descriptionShort: "倾血逆冲、煞重则爆发翻涌的血蛊。",
    descriptionLore: "血道秘篇：寻常血蛊顺血而行，此蛊偏要倒着来。它咬开主脉，令血不外流而内逆，逼出沉积的旧煞一并外放。代价是元气大伤，所得却是煞气倍涌、一击如崩堤。绛妄说：「敢用逆血者，是把命押在下一刀上。」",
    habitat: "生于血脉逆乱、横死不甘者的残骸。", feeding: "饮逆流之血与翻涌的旧煞。", temperament: "暴烈难驯，喂则索更多，稍纵即反噬。",
    evolution: "逆煞难收，常自行崩解或并入更凶的血道异蛊。", synergy: "与「血刃蛊」「噬心蛊」同囊，煞越厚逆血越猛。", counteredBy: "极耗主血，连出则力竭；惧疗血与速决。",
    dropsFrom: "通用进阶牌池(战后奖励)、血道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "失去 5 点生命，造成 16 + 血煞×2 点伤害，获得 1 层血煞。", image: "assets/codex/gu/reverse-blood-gu.webp",
  },
  {
    id: "gu_shellremnant", category: "gu", cardKey: "shellRemnant",
    name: "残壳蛊", alias: "弃甲虫", rarity: "灵蛊", faction: "护身", type: "防御", stage: "灵蛊·残形",
    descriptionShort: "受创愈坚、以残壳叠甲的护蛊。",
    descriptionLore: "护身残页：此蛊以蜕下的旧壳为食，越是破碎的甲它越啃得欢。临敌时但凡主受一击，它便急急取残壳补缀，伤口一开、甲反更厚。蛊师笑称：「它是越打越精神的犟脾气。」",
    habitat: "栖于蜕壳堆、败甲废铠的残骸之间。", feeding: "啃食破碎旧甲与蜕壳。", temperament: "倔而韧，受激则盛，安逸则懒。",
    evolution: "可炼为「蜕甲蛊」，弃旧迎新、甲随蜕生。", synergy: "与「铁皮蛊」「蜕壳蛊」叠甲，受创循环愈厚。", counteredBy: "未受创时所得有限；惧蚀甲与破甲连击。",
    dropsFrom: "通用构筑牌(奖励与蛊坊)。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 6 点防御；若本回合已受伤，额外获得 6 点防御。", image: "assets/codex/gu/broken-shell-gu.webp",
  },
  {
    id: "gu_reversepath", category: "gu", cardKey: "reversePath",
    name: "逆途蛊", alias: "踏命引", rarity: "灵蛊", faction: "命途", type: "辅助", stage: "灵蛊·途形",
    descriptionShort: "零耗积势、攻守相替的命势辅蛊。",
    descriptionLore: "逆命残篇：天命之人顺途而行，无名逆命者却只能逆途夺命。此蛊不耗真元，只在主每一次攻守转换间，悄悄替他攒下一分命势、一缕护气。途虽逆，步步皆数。「顺者天与，逆者自取。」",
    habitat: "无定所，附于不肯认命、屡败屡起之人。", feeding: "不食血肉，汲主攻守交替间漏出的命势。", temperament: "沉静而执，势弱不弃，步步为营。",
    evolution: "势数纯熟可与「断命蛊」「定数蛊」共结命势环。", synergy: "与「命线蛊」相济：先以逆途积势，再以命线收割。", counteredBy: "本身无伤无防峰值，惧被速攻打断节奏。",
    dropsFrom: "无名逆命者起手蛊囊、命势流蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 3 点防御，并获得 1 层命势。", image: "assets/codex/gu/inverse-path-gu.webp",
  },
  {
    id: "gu_moltingshell", category: "gu", cardKey: "moltingShell",
    name: "蜕壳蛊", alias: "褪甲蜕", rarity: "灵蛊", faction: "毒道", type: "防御", stage: "灵蛊·蜕形",
    descriptionShort: "御伤兼借毒生机的毒道护蛊。",
    descriptionLore: "毒道杂篇：此蛊半毒半甲，蜕壳之际既能护体，又能从敌身的毒里汲一线生机。青蟒一脉以毒铺路、以蜕壳守身，毒越深，它退得越从容。「敌中我毒，我便从它的烂处取一口活路。」",
    habitat: "潜居瘴泽蜕壳、毒藤盘结之处。", feeding: "食蜕壳，亦从中毒之敌身上汲毒为养。", temperament: "阴而稳，善守善退，不喜强攻。",
    evolution: "可与「腐瘴蛊」共生，蜕中带毒、守中藏蚀。", synergy: "与「青瘴蛊」「虫群蛊」铺毒在前，蜕壳愈从容。", counteredBy: "敌不中毒时只是寻常护甲；惧破甲与净毒。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 8 点防御；若敌人已中毒，抽 1 张牌。", image: "assets/codex/gu/molting-shell-gu.webp",
  },
  {
    id: "gu_poisonreturn", category: "gu", cardKey: "poisonReturn",
    name: "返毒蛊", alias: "蝎返瘴", rarity: "灵蛊", faction: "毒道", type: "攻击", stage: "灵蛊·蝎形",
    descriptionShort: "毒深则反噬、借敌之毒重击的毒蛊。",
    descriptionLore: "毒道残卷：此蛊形如毒蝎，尾悬一囊浊瘴。寻常一蜇不过小伤，可一旦敌身积毒已深，它便将那毒尽数勾出、连本带利返还其身。青蟒门人最爱在敌烂透时唤它收尾——「你欠下的毒，该连利还了。」",
    habitat: "盘踞毒潭蝎窟、瘴气最浓的死水边。", feeding: "噬瘴气与中毒之物，毒越浓越肥。", temperament: "蛰伏耐等，毒不深不动，一动即收命。",
    evolution: "瘴极可向毒道异蛊蜕形，一返九层。", synergy: "与「青瘴蛊」「腐瘴蛊」「虫群蛊」叠毒在前，返毒爆发倍增。", counteredBy: "敌毒浅时威胁有限；惧净毒断瘴与速攻。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 6 点伤害；若敌人中毒不少于 8 层，额外造成 8 点伤害。", image: "assets/codex/gu/return-poison-gu.webp",
  },

  /* ===== 生态蛊(gu 文件夹有立绘、游戏内暂未实装为战斗蛊牌) ===== */
  {
    id: "eco_bonebell", category: "eco", cardKey: "",
    name: "骨铃蛊", alias: "招魂铃", rarity: "异蛊", faction: "骨道", type: "生态", stage: "异蛊·骨形",
    descriptionShort: "颅骨悬铃、铃响则魂动的骨道异蛊。",
    descriptionLore: "骨道异闻：枯井深处常拾得一串骨铃，乃此蛊蜕下的躯壳。活蛊以颅骨为腹、以骨刺为足，行动时铃声幽幽，凡闻者皆觉有人在背后数自己尚余几年寿。世人讳称它「招魂的更夫」。",
    habitat: "盘踞枯井、乱葬、断碑之下的骨堆。", feeding: "啃食陈骨与残念，铃声越密食得越欢。", temperament: "阴冷好静，受惊则铃乱、骨刺尽张。",
    evolution: "（未实装，演化路线待考。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备，游戏内尚无对应蛊牌。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/bonebell-gu.webp",
  },
  {
    id: "eco_chaosbee", category: "eco", cardKey: "",
    name: "乱蜂蛊", alias: "千刺潮", rarity: "灵蛊", faction: "虫群", type: "生态", stage: "灵蛊·蜂形",
    descriptionShort: "群刺如雨、红目凶悍的虫群生态蛊。",
    descriptionLore: "虫群杂记：此蜂不结一巢，而以蛊母为心、聚潮成阵。怒时尾刺如雨倾射，金纹赤目，所过之处寸草溃烂。命途中所遇之「乱蜂蛊潮」，便是此蛊成势之相。养之为牌者尚未现世。",
    habitat: "聚居断崖蜂岩、腐花毒蜜之地。", feeding: "采毒花、噬腐蜜，亦食同类残躯。", temperament: "暴躁群涌，一激则倾巢，难独驯。",
    evolution: "（未实装；其成潮之相见敌怪「乱蜂蛊潮」。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备；游戏内现以敌怪「乱蜂蛊潮」登场，尚无玩家蛊牌。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/chaos-bee-gu.webp",
  },
  {
    id: "eco_bloodmarsh", category: "eco", cardKey: "",
    name: "血沼蛊", alias: "沉血蚿", rarity: "异蛊", faction: "血道", type: "生态", stage: "异蛊·沼形",
    descriptionShort: "粗躯倒刺、生于血沼深处的血道生态蛊。",
    descriptionLore: "百血录·异闻：生于血沼深渊，躯粗如管、满覆倒刺，吸血而肥、沉血而眠。它不挑食，过路的活物、沉底的旧血、连同沼里未散的怨气，都一并吞下。立绘题「百血录·血道类」，凶名在外，惜游戏内暂未成牌。",
    habitat: "沉眠血沼、尸血淤积的深渊底泥。", feeding: "吸活血、吞旧血，越腥越沉越肥。", temperament: "迟缓而贪，醒则吞噬一切，难近难驯。",
    evolution: "（未实装，血道演化路线待考。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备，游戏内尚无对应蛊牌(近似的有血潮蛊/血月蛊，非同一只)。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/bloodmarsh-gu.webp",
  },
  /* ===== V0.9.7 第一层 · 命途塔敌怪图谱（category:"enemy"，带 enemyId 供「已遇」解锁，立绘走 assets/portraits 真实文件） ===== */
  {
    id: "enemy_shanxiao", category: "enemy", cardKey: "", enemyId: "shanxiao",
    name: "山魈", alias: "塔中凶兽", rarity: "普通", faction: "凶兽", type: "敌怪", stage: "命途塔·塔阶",
    descriptionShort: "伏于阴风塔阶、饮血裂石的山鬼凶兽。",
    descriptionLore: "命途塔录：山魈本是栖于荒山的山鬼，被命途塔的蛊息引入塔中，化作守阶凶兽。阴风穿塔，兽啸逼近，它伏在阴影里窥伺来者破绽，一爪饮血、一扑裂石。",
    habitat: "盘踞命途塔下层阴暗塔阶。", feeding: "饮血裂石，啖入塔修者之血肉。", temperament: "凶蛮善伏，蓄势而后裂扑。",
    evolution: "积腐可堕为「腐皮山魈」。", synergy: "与塔阶同类轮番扑杀。", counteredBy: "惧速攻，避其蓄势重击。",
    dropsFrom: "第一层·命途塔 普通战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-shanxiao-web.jpg",
  },
  {
    id: "enemy_rottenshanxiao", category: "enemy", cardKey: "", enemyId: "rottenShanxiao",
    name: "腐皮山魈", alias: "腐毒凶兽", rarity: "普通", faction: "凶兽", type: "敌怪", stage: "命途塔·塔阶",
    descriptionShort: "腐皮剥落、爪缝滴毒的塔阶凶兽。",
    descriptionLore: "命途塔录：腐皮山魈是被塔中瘴息浸烂的山魈，腐皮剥落，烂尾拖地，爪缝里滴着青黑毒液。它伏在塔阶旁，腐息蓄毒，一爪下去伤口便溃烂不止。",
    habitat: "蛰伏命途塔潮腐的塔阶角落。", feeding: "啖腐肉、吸塔中瘴息。", temperament: "阴毒迟缓，腐息缠身。",
    evolution: "由「山魈」积腐堕化而成。", synergy: "与塔阶凶兽同列施毒。", counteredBy: "惧净毒与速决，避其叠毒。",
    dropsFrom: "第一层·命途塔 普通战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-shanxiao-web.jpg",
  },
  {
    id: "enemy_bloodwolf", category: "enemy", cardKey: "", enemyId: "bloodwolf",
    name: "异变血狼", alias: "血沼凶兽", rarity: "普通", faction: "凶兽", type: "敌怪", stage: "命途塔·血径",
    descriptionShort: "踏煞雾、以煞气为食的血纹凶狼。",
    descriptionLore: "命途塔录：异变血狼踏着猩红煞雾逼近，骨刺间挂着未干血迹。它本是寻常狼，吞食塔中煞气后异变，血雾贴地、狼嚎裂心，饥噬之下连骨带血一并吞下。",
    habitat: "游走命途塔煞雾弥漫的血径。", feeding: "以煞气为食，饥则噬血。", temperament: "贪噬凶猛，逐血长嚎。",
    evolution: "可异变为「赤鬃血狼」。", synergy: "与血狼同类成群猎杀。", counteredBy: "惧速杀，避其饥噬重击。",
    dropsFrom: "第一层·命途塔 普通战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-bloodwolf-web.jpg",
  },
  {
    id: "enemy_redmanebloodwolf", category: "enemy", cardKey: "", enemyId: "redManeBloodwolf",
    name: "赤鬃血狼", alias: "赤鬃凶兽", rarity: "普通", faction: "凶兽", type: "敌怪", stage: "命途塔·血径",
    descriptionShort: "赤鬃燃血、伤重愈狂的逐魂血狼。",
    descriptionLore: "命途塔录：赤鬃血狼周身赤鬃如燃血，绕着来者低伏游走。它半身染血后只会更凶——赤鬃怒嚎一起，扑咬便如疯魔，伤得越重，狂得越甚。",
    habitat: "游猎命途塔血径深处。", feeding: "逐血而食，越战越饥。", temperament: "亢狂嗜杀，残血则暴怒。",
    evolution: "由「异变血狼」染血而成。", synergy: "与血纹狼王同源凶猎。", counteredBy: "惧高爆速杀，避其狂怒相位。",
    dropsFrom: "第一层·命途塔 普通战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-bloodwolf-web.jpg",
  },
  {
    id: "enemy_bloodwolfelite", category: "enemy", cardKey: "", enemyId: "bloodwolfElite",
    name: "血纹狼王", alias: "命途精英", rarity: "精英", faction: "凶兽", type: "敌怪·精英", stage: "命途塔·精英",
    descriptionShort: "血纹伏地、追魂裂骨的塔中狼王。",
    descriptionLore: "命途塔录：血纹狼王自塔影中缓步踏出，背脊血纹如活虫般起伏。它是塔阶凶兽之首，血月嚎叫聚甲、裂骨扑杀拦路，越是低血者，越被它追魂撕咬。",
    habitat: "盘踞命途塔精英试炼之地。", feeding: "猎食塔修者，血纹饮血而盛。", temperament: "凶悍狡狂，残血则血纹狂化。",
    evolution: "（命途精英，暂无玩家蛊牌。）", synergy: "为尸盘监守拦路开道。", counteredBy: "惧稳守高爆，避其低血追杀。",
    dropsFrom: "第一层·命途塔 精英战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-bloodwolf-web.jpg",
  },
  {
    id: "enemy_beeswarm", category: "enemy", cardKey: "", enemyId: "beeswarm",
    name: "毒蜂蛊群", alias: "失控虫群", rarity: "普通", faction: "毒道", type: "敌怪", stage: "命途塔·虫巢",
    descriptionShort: "毒翅蔽灯、群蜂如潮的失控蛊群。",
    descriptionLore: "命途塔录：无数毒蜂纠缠成一张狰狞虫面，幽绿毒雾自蜂群间滴落。它们本是养蛊人豢养的工蜂，蛊主一死便失控成灾，振翅聚毒，毒针攒射如蔽天暴雨。",
    habitat: "盘旋命途塔废弃虫巢、破灯残烛之间。", feeding: "采毒酿瘴，啖入塔修者之血。", temperament: "狂乱群居，受激则倾巢突袭。",
    evolution: "失控可乱化为「乱蜂蛊潮」。", synergy: "群蜂叠毒、以多欺寡。", counteredBy: "惧范围与速攻，散则力竭。",
    dropsFrom: "第一层·命途塔 普通战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-beeswarm-web.jpg",
  },
  {
    id: "enemy_wildbeetide", category: "enemy", cardKey: "", enemyId: "wildBeeTide",
    name: "乱蜂蛊潮", alias: "暴乱虫群", rarity: "普通", faction: "毒道", type: "敌怪", stage: "命途塔·虫巢",
    descriptionShort: "乱翅撞灯、双刺乱鸣的暴乱毒云。",
    descriptionLore: "命途塔录：乱蜂蛊潮并非一群虫，而像一团被怨念搅碎的毒云。它没有蜂面、没有阵形，只剩乱翅撞灯、双刺乱鸣，毒翅擦身即留余毒，聚形又散，难以尽除。",
    habitat: "翻涌于命途塔阴风穿堂的破巢。", feeding: "吞瘴噬怨，越乱越盛。", temperament: "暴乱无形，聚散无常。",
    evolution: "由「毒蜂蛊群」失控暴乱而成。", synergy: "与毒蜂同巢压迫铺毒。", counteredBy: "惧速决，免其连蜇叠毒。",
    dropsFrom: "第一层·命途塔 普通战。", unlockCondition: "于命途塔遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-beeswarm-web.jpg",
  },

  /* ===== V0.9.6 第二层 · 敌怪图谱（category:"enemy"，带 enemyId 供「已遇」解锁，无立绘走暗色占位） ===== */
  {
    id: "enemy_rotleaf", category: "enemy", cardKey: "", enemyId: "rotleafGu",
    name: "腐叶蛊虫", alias: "涎毒蜗", rarity: "普通", faction: "毒道", type: "敌怪", stage: "瘴林·杂蛊",
    descriptionShort: "蜷于烂叶、啃噬带毒的瘴林杂蛊。",
    descriptionLore: "瘴林录：腐叶蛊虫终日埋首腐叶，背壳一层薄薄青黏，所过之处叶脉尽黑。单只不足为患，可瘴林之中从无单只——它们以毒铺路，等你慢慢烂下去。",
    habitat: "栖于瘴林腐叶堆、终年不见日的湿沟。", feeding: "啃腐叶、吸瘴气，越湿越肥。", temperament: "蛰伏怯战，受激则成片涌出。",
    evolution: "积毒可蜕为「青瘴寄生」。", synergy: "与瘴林同类叠毒铺场。", counteredBy: "惧火与速攻，毒未深已亡。",
    dropsFrom: "第二层·瘴林深径 普通战。", unlockCondition: "于瘴林遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/rot-leaf-gu-insect.webp",
  },
  {
    id: "enemy_miasmaparasite", category: "enemy", cardKey: "", enemyId: "miasmaParasite",
    name: "青瘴寄生", alias: "附骨瘴", rarity: "普通", faction: "毒道", type: "敌怪", stage: "瘴林·寄生",
    descriptionShort: "附骨噬毒、专挑中毒者下口的瘴蛊。",
    descriptionLore: "瘴林录：青瘴寄生半透的躯体里游着幽绿，它不爱鲜活，只爱已经中毒、正在腐烂的血肉——你身上的毒越深，它咬得越欢。",
    habitat: "潜伏瘴林湿洼、毒藤盘结的阴处。", feeding: "噬中毒之血肉，借毒滋养。", temperament: "阴忍善缠，毒发无声。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与施毒同类成阵。", counteredBy: "惧净毒与爆发速决。",
    dropsFrom: "第二层·瘴林深径 普通战。", unlockCondition: "于瘴林遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/green-miasma-parasite.webp",
  },
  {
    id: "enemy_poisonvinecorpse", category: "enemy", cardKey: "", enemyId: "poisonVineCorpse",
    name: "毒藤尸", alias: "藤缠腐尸", rarity: "普通", faction: "毒道", type: "敌怪", stage: "瘴林·尸傀",
    descriptionShort: "被毒藤贯穿、挥拳带毒的腐尸傀。",
    descriptionLore: "瘴林录：毒藤尸本是误入瘴林的活人，被瘴藤贯体提起，化作半藤半尸的傀儡。它残存的拳力裹着倒刺毒藤，伤重时反而暴走。",
    habitat: "立于瘴林深径、藤网密结之地。", feeding: "由寄主毒藤汲养，无须进食。", temperament: "迟缓而凶，受创愈狂。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与执灯者同列瘴林精锐。", counteredBy: "惧速杀，免其暴走相位。",
    dropsFrom: "第二层·瘴林深径 普通战。", unlockCondition: "于瘴林遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/poison-vine-thrall.webp",
  },
  {
    id: "enemy_miasmalantern", category: "enemy", cardKey: "", enemyId: "miasmaLanternEliteGu",
    name: "瘴林执灯者", alias: "鬼灯瘴使", rarity: "精英", faction: "毒道", type: "敌怪·精英", stage: "瘴林·精英",
    descriptionShort: "提鬼灯引瘴、灯过成毒的瘴林精英。",
    descriptionLore: "瘴林录：执灯者提一盏青焰鬼灯巡行瘴林，灯火所照，瘴气如潮翻涌。传言灯中燃的是迷途者的魂，魂尽则瘴散——而瘴从未散过。",
    habitat: "巡行瘴林深处，灯不离手。", feeding: "焚魂引瘴，以瘴为食。", temperament: "冷峻执拗，逼近则狂瘴四溢。",
    evolution: "（生态精英，暂无玩家蛊牌。）", synergy: "为百瘴母蛊开路。", counteredBy: "惧高爆速攻，避其叠毒滚雪。",
    dropsFrom: "第二层·瘴林深径 精英战。", unlockCondition: "于瘴林遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/miasma-lantern-keeper.webp",
  },
  {
    id: "enemy_bloodleech", category: "enemy", cardKey: "", enemyId: "bloodLeechSwarm",
    name: "血蛭群", alias: "饱血潮", rarity: "普通", faction: "血道", type: "敌怪", stage: "血沼·蛭群",
    descriptionShort: "成片涌出、吸血回身的血沼蛭潮。",
    descriptionLore: "血沼录：血蛭群从沼泥成片钻出，吸饱血的躯体油亮发红。它们不求一击毙命，只求附身吸血——你流的每一滴，都成了它们的命。",
    habitat: "潜伏血沼浅滩、尸血淤积的泥层。", feeding: "吸活血而肥，越腥越聚。", temperament: "无主而贪，势成则倾巢。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与血沼同类压迫低血者。", counteredBy: "惧范围与速攻，散则力竭。",
    dropsFrom: "第二层·血沼沉渊 普通战。", unlockCondition: "于血沼遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/red-marsh-leech-swarm.webp",
  },
  {
    id: "enemy_brokenmeridian", category: "enemy", cardKey: "", enemyId: "brokenMeridianGu",
    name: "断脉蛊徒", alias: "自戕血修", rarity: "普通", faction: "血道", type: "敌怪", stage: "血沼·血修",
    descriptionShort: "自断经脉、以血换力的血道蛊徒。",
    descriptionLore: "血沼录：断脉蛊徒割开自己的腕脉，任血珠凝成赤刃。他越是淌血，出手越狠——血道一脉的疯，从这一刀自戕里就看得分明。",
    habitat: "游荡血沼血径、血祭遗坛附近。", feeding: "以自身之血饲蛊换力。", temperament: "亢奋自残，血少则更凶。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与血衣祭蛊者同源。", counteredBy: "惧护甲与稳守，耗其自损。",
    dropsFrom: "第二层·血沼沉渊 普通战。", unlockCondition: "于血沼遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/severed-meridian-cultist.webp",
  },
  {
    id: "enemy_bloodmudgolem", category: "enemy", cardKey: "", enemyId: "bloodMudGolem",
    name: "血泥傀", alias: "沼底血傀", rarity: "普通", faction: "血道", type: "敌怪", stage: "血沼·泥傀",
    descriptionShort: "血泥成形、吸沼自补的血沼傀儡。",
    descriptionLore: "血沼录：血泥傀由凝结的血泥层层堆塑，受创的缺口会再吸沼底浊血补回。它笨重而执拗，最是磨人——你劈开的，它一并吸回去。",
    habitat: "盘踞血沼深处、血泥淤积之地。", feeding: "吸沼血自补，受创愈贪。", temperament: "迟缓固执，残血则暴凝。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与血沼同类拖延耗血。", counteredBy: "惧高爆一波带走，免其回血。",
    dropsFrom: "第二层·血沼沉渊 普通战。", unlockCondition: "于血沼遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/blood-mud-puppet.webp",
  },
  {
    id: "enemy_bloodrobepriest", category: "enemy", cardKey: "", enemyId: "bloodRobePriestEliteGu",
    name: "血衣祭蛊者", alias: "血祭司", rarity: "精英", faction: "血道", type: "敌怪·精英", stage: "血沼·精英",
    descriptionShort: "披血衣、以命饲蛊的血沼精英。",
    descriptionLore: "血沼录：血衣祭蛊者披一件浸透鲜血的法袍，每挥洒一击都先割开自己。他视痛楚为祭品，你越虚弱，他的血祭便压得越狠。",
    habitat: "守在血沼血祭坛前，血衣不离身。", feeding: "以自身与祭品之血饲蛊。", temperament: "狂信自残，逼近则血祭狂涌。",
    evolution: "（生态精英，暂无玩家蛊牌。）", synergy: "为血衣蛊母开路。", counteredBy: "惧稳守高血，避其低血压迫。",
    dropsFrom: "第二层·血沼沉渊 精英战。", unlockCondition: "于血沼遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/bloodrobe-gu-sacrificer.webp",
  },

  /* ===== V0.9.7 第一层 · 命途塔首领（category:"boss"，带 enemyId） ===== */
  {
    id: "boss_corpsepuppet", category: "boss", cardKey: "", enemyId: "corpsepuppet",
    name: "尸盘监守", alias: "塔顶尸盘监守", rarity: "首领", faction: "凶兽", type: "首领", stage: "命途塔·塔顶",
    descriptionShort: "踞塔顶尸盘、万蛊守门的命途塔之主。",
    descriptionLore: "命途塔残卷：尸盘监守自腐朽王座上起身，胸腔蛊火照亮塔顶尸盘的累累白骨。它是这座命途塔的守门之主，尸盘转动，整座塔随之震颤——蛊火吐息焚毒，尸盘蓄势一击镇塔。",
    habitat: "踞守命途塔最高处的尸盘王座。", feeding: "以塔中亡魂与万蛊豢养尸火。", temperament: "沉寂威重，蓄势则万蛊俱动。",
    evolution: "破之则塔顶裂开向下暗径，通往第二层。", synergy: "麾下尽是命途塔守阶凶兽。", counteredBy: "惧持续压制；蓄势重击须及时打断。",
    dropsFrom: "第一层·命途塔 塔顶 Boss。", unlockCondition: "于塔顶遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/enemy-corpsepuppet-web.jpg",
  },

  /* ===== V0.9.6 第二层 · 首领残卷（category:"boss"，带 enemyId） ===== */
  {
    id: "boss_miasmamother", category: "boss", cardKey: "", enemyId: "miasmaMotherBoss",
    name: "百瘴母蛊", alias: "万毒同巢", rarity: "首领", faction: "毒道", type: "首领", stage: "瘴林·之主",
    descriptionShort: "腹孕百瘴、半血苏醒的瘴林之主。",
    descriptionLore: "瘴林残卷：百瘴母蛊是整片瘴林的源头，臃肿的腹囊里翻涌上百种瘴毒。它平日昏沉，唯有命悬一线时「瘴母苏醒」，毒雾遮天，誓要与来犯者同烂于此。",
    habitat: "盘踞瘴林最深的母蛊巢穴。", feeding: "吞噬一切腐物与瘴气孕育新毒。", temperament: "慵懒贪睡，半血则暴怒苏醒。",
    evolution: "半血触发「瘴母苏醒」相位，施毒大增。", synergy: "麾下尽是瘴林毒蛊。", counteredBy: "惧高爆速杀；拖延则毒层失控。",
    dropsFrom: "第二层·瘴林深径 路线 Boss。", unlockCondition: "于瘴林遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/hundred-miasma-mother-gu.webp",
  },
  {
    id: "boss_bloodrobemother", category: "boss", cardKey: "", enemyId: "bloodRobeMotherBoss",
    name: "血衣蛊母", alias: "血债血偿", rarity: "首领", faction: "血道", type: "首领", stage: "血沼·之主",
    descriptionShort: "血衣覆身、越战越亢的血沼之主。",
    descriptionLore: "血沼残谱：血衣蛊母端坐血池之上，周身血衣无风自动。她以搏杀为飨，你越是拼命，她越是亢奋；半血时「血衣覆身」，血债加倍奉还。",
    habitat: "端坐血沼深渊的血池之心。", feeding: "饮搏杀之血、纳祭蛊者之命。", temperament: "亢奋嗜战，半血则血衣覆身。",
    evolution: "半血触发「血衣覆身」相位，吸血压迫大增。", synergy: "麾下尽是血沼血道之徒。", counteredBy: "惧高血稳推；低血则被反噬。",
    dropsFrom: "第二层·血沼沉渊 路线 Boss。", unlockCondition: "于血沼遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/bloodrobe-gu-mother.webp",
  },

  /* ===== V0.9.6 第二层 · 生态条目（category:"eco"，沿用现有 eco 渲染，恒显示） ===== */
  {
    id: "eco_miasmaforest", category: "eco", cardKey: "",
    name: "瘴林", alias: "百瘴深径", rarity: "异蛊", faction: "毒道", type: "生态", stage: "生态·瘴林",
    descriptionShort: "终年瘴气不散、毒越积越深的生态深径。",
    descriptionLore: "生态志·瘴林：命途塔下第一层深径，终年笼罩在百瘴母蛊吐出的毒雾里。腐叶、毒藤、寄生瘴虫层层叠生，越往深处毒越浓。入此径者，须以毒制毒，方能在烂尽之前杀出。",
    habitat: "命途塔第二层 · 瘴林路线全域。", feeding: "（生态环境，非可养之蛊。）", temperament: "阴湿致命，久留必腐。",
    evolution: "（生态条目，暂无演化。）", synergy: "（生态条目，暂无战斗联动。）", counteredBy: "（生态条目。）",
    dropsFrom: "第二层瘴林路线，进入即录。", unlockCondition: "暂作生态条目展示。",
    gameplayEffect: "", image: "",
  },
  {
    id: "eco_bloodmarsh_zone", category: "eco", cardKey: "",
    name: "血沼", alias: "沉血深渊", rarity: "异蛊", faction: "血道", type: "生态", stage: "生态·血沼",
    descriptionShort: "尸血淤积、以命饲蛊的血道生态深渊。",
    descriptionLore: "生态志·血沼：命途塔下另一条歧路，尸血与怨气在此沉积成沼。血道蛊修在此自戕饲蛊，沼中之物嗜血成性，你越虚弱，它们越亢奋。血衣蛊母端坐其心，血债血偿。",
    habitat: "命途塔第二层 · 血沼路线全域。", feeding: "（生态环境，非可养之蛊。）", temperament: "嗜血贪婪，低血者危。",
    evolution: "（生态条目，暂无演化。）", synergy: "（生态条目，暂无战斗联动。）", counteredBy: "（生态条目。）",
    dropsFrom: "第二层血沼路线，进入即录。", unlockCondition: "暂作生态条目展示。",
    gameplayEffect: "", image: "",
  },

  /* ===== V0.9.8 第三层 · 首领残卷（category:"boss"，带 enemyId） ===== */
  {
    id: "boss_boneNestGuardian", category: "boss", cardKey: "", enemyId: "boneNestGuardianBoss",
    name: "骨巢守墓王", alias: "死骨共鸣", rarity: "首领", faction: "护身", type: "首领", stage: "骨塔·之主",
    descriptionShort: "踞万骨高陵、召卫蓄力镇陵的骨塔之主。",
    descriptionLore: "骨塔残卷：骨巢守墓王盘踞于万骨堆成的高陵之巅，胸腔骨火幽幽，召卫叠甲、蓄力重击层层压来。它守的不是宝藏，而是这一陵亡骨的安眠——凡惊扰者，皆添一具白骨。半血时「骨巢开裂」，死骨共鸣，压势更狠。",
    habitat: "踞守骨塔高陵最深的骨巢王座。", feeding: "以陈骨残念与亡魂共鸣豢养骨火。", temperament: "沉寂威重，受扰则召卫蓄力齐发。",
    evolution: "半血触发「骨巢开裂」相位，召卫与蓄力压势大增。", synergy: "麾下尽是骨塔朽甲与骨甲蛊卫。", counteredBy: "惧持续压制；召卫蓄力须及时打断，纯毒难以速杀。",
    dropsFrom: "第三层·骨塔高陵 路线 Boss。", unlockCondition: "于骨塔遭遇即录入。",
    gameplayEffect: "召卫叠甲、蓄力重击镇陵，半血触发「骨巢开裂」强化；具部分毒抗，并会吞毒化为自身回复。", image: "assets/portraits/bone-nest-tomb-king.webp",
  },
  {
    id: "boss_calamityQueen", category: "boss", cardKey: "", enemyId: "calamityQueenBoss",
    name: "灾厄蜂后", alias: "万毒之源", rarity: "首领", faction: "毒道", type: "首领", stage: "蜂窟·之主",
    descriptionShort: "伏于魔巢核心、万翅同振的蜂窟之主。",
    descriptionLore: "蜂窟残卷：灾厄蜂后伏于魔巢最深的核心，麾下蜂群无穷无尽。她以毒刺与多段齐落压制来者，半血之后掀起「蜂群暴动」，万翅同振，整座魔巢都成了她的毒潮。世人讳称它为万毒之源。",
    habitat: "伏于蜂窟魔巢核心的蜂后巢室。", feeding: "以毒蜜与孵巢蜂群孕育无尽蜂潮。", temperament: "慵懒孕蜂，半血则掀蜂群暴动。",
    evolution: "半血触发「蜂群暴动」相位，蜂群层数与毒刺压势暴增。", synergy: "麾下尽是蜂窟毒蜂与蜂巢虫蛊。", counteredBy: "惧高爆速杀；拖延则蜂群层数失控。",
    dropsFrom: "第三层·蜂窟魔巢 路线 Boss。", unlockCondition: "于蜂窟遭遇即录入。",
    gameplayEffect: "", image: "assets/portraits/calamity-bee-queen.webp",
  },

  /* ===== V0.9.8 第三层 · 敌怪图谱（category:"enemy"，带 enemyId 供「已遇」解锁） ===== */
  {
    id: "enemy_bonebellGu", category: "enemy", cardKey: "", enemyId: "bonebellGu",
    name: "骨铃巡蛊", alias: "乱铃扰神", rarity: "普通", faction: "护身", type: "敌怪", stage: "骨塔·杂蛊",
    descriptionShort: "背壳垂铃、摇铃乱神的骨塔杂蛊。",
    descriptionLore: "骨塔录：骨铃巡蛊背壳垂着一串森白骨铃，每一次摇动都在你耳中织出杂音。它不以力胜，专以乱铃扰你心神，趁你恍惚之际啄上一口。",
    habitat: "游荡骨塔高陵的骨堆缝隙。", feeding: "啃陈骨残念，铃响越密食得越欢。", temperament: "阴冷好扰，受激则乱铃齐摇。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与骨塔同类以乱铃配合蓄力。", counteredBy: "惧速决，免其乱铃扰神。",
    dropsFrom: "第三层·骨塔高陵 普通战。", unlockCondition: "于骨塔遭遇即录入。",
    gameplayEffect: "摇响骨铃扰乱心神（乱铃），并蓄势加重下一击。", image: "assets/portraits/bone-bell-patrol-gu.webp",
  },
  {
    id: "enemy_skeletonPuppetGu", category: "enemy", cardKey: "", enemyId: "skeletonPuppetGu",
    name: "朽甲蛊兵", alias: "蓄力重击", rarity: "普通", faction: "护身", type: "敌怪", stage: "骨塔·列卒",
    descriptionShort: "残骨朽甲拼缀、蓄力重砸的骨塔列卒。",
    descriptionLore: "骨塔录：朽甲蛊兵周身覆着朽烂旧甲，由残骨与蛊丝拼缀成形，举起骨锤时关节咔咔作响。它动作迟缓却力大无穷，一旦蓄满力气，重砸下来便能裂石碎甲；朽甲护身，亦削减所中毒性。",
    habitat: "列阵骨塔高陵的朽甲阵。", feeding: "由骨巢蛊丝牵引，无须进食。", temperament: "迟缓固执，蓄力则一击倾尽。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与骨甲蛊卫同列拦路。", counteredBy: "蓄力重砸受够阈值伤害可打断，未断则吃满一击。",
    dropsFrom: "第三层·骨塔高陵 普通战。", unlockCondition: "于骨塔遭遇即录入。",
    gameplayEffect: "缩骨蓄甲后蓄力重砸（蓄力可在受够阈值伤害后打断）；朽甲在身具部分毒抗。", image: "assets/portraits/rotten-armor-gu-soldier.webp",
  },
  {
    id: "enemy_boneArmorGuardGu", category: "enemy", cardKey: "", enemyId: "boneArmorGuardGu",
    name: "骨甲蛊卫", alias: "甲坚击重", rarity: "普通", faction: "护身", type: "敌怪", stage: "骨塔·甲士",
    descriptionShort: "层叠骨甲、有甲愈凶的骨塔甲士。",
    descriptionLore: "骨塔录：骨甲蛊卫通体覆着层叠骨甲，护甲未破时出手格外沉重。它以甲为势，护甲在身便有甲愈凶，残血时更暴坚反扑。",
    habitat: "镇守骨塔高陵的甲士列。", feeding: "啃食金石骨屑修补骨甲。", temperament: "迟钝而坚，残血则骨甲暴坚。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与朽甲蛊兵同列叠甲压迫。", counteredBy: "惧破甲与高爆；护甲未破前输出难以突破。",
    dropsFrom: "第三层·骨塔高陵 普通战。", unlockCondition: "于骨塔遭遇即录入。",
    gameplayEffect: "覆甲固身后，自身有护甲时攻击附加额外伤害（甲坚击重）；骨甲在身具较强毒抗。", image: "assets/portraits/bone-armor-gu-guard.webp",
  },
  {
    id: "enemy_boneCommanderElite", category: "enemy", cardKey: "", enemyId: "boneCommanderElite",
    name: "骨塔执令者", alias: "执令加身", rarity: "精英", faction: "护身", type: "敌怪·精英", stage: "骨塔·精英",
    descriptionShort: "举令骨杖、号令尸群的骨塔精英。",
    descriptionLore: "骨塔录：骨塔执令者举着一截发令骨杖，杖头骨纹一亮，便有重击随令而至。它以执令印记自加号令，越战越厉，残血时厉令狂涌。",
    habitat: "统辖骨塔高陵精英试炼之地。", feeding: "以号令凝聚尸群骨煞为养。", temperament: "威厉狠戾，残血则厉令狂涌。",
    evolution: "（骨塔精英，暂无玩家蛊牌。）", synergy: "为骨巢守墓王号令开道。", counteredBy: "惧高爆速杀，避其执令累加重击。",
    dropsFrom: "第三层·骨塔高陵 精英战。", unlockCondition: "于骨塔遭遇即录入。",
    gameplayEffect: "以执令印记自加号令、攻势随令累增；残血厉令狂涌。", image: "assets/portraits/bone-tower-commander.webp",
  },
  {
    id: "enemy_venomBeeGu", category: "enemy", cardKey: "", enemyId: "venomBeeGu",
    name: "毒蜂蛊", alias: "毒针连刺", rarity: "普通", faction: "毒道", type: "敌怪", stage: "蜂窟·杂蛊",
    descriptionShort: "悬翅乱舞、针针带毒的蜂窟杂蛊。",
    descriptionLore: "蜂窟录：毒蜂蛊振翅悬于半空，腹尾毒针滴着幽绿黏液，专挑空门连刺。你越是残血，它的渗毒蜇刺扎得越狠。",
    habitat: "盘旋蜂窟魔巢的巢道空隙。", feeding: "采毒花酿瘴，啖入来者之血。", temperament: "轻捷乱舞，专挑空门连刺。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与蜂巢虫蛊同巢铺毒。", counteredBy: "惧速决，免其连刺叠毒。",
    dropsFrom: "第三层·蜂窟魔巢 普通战。", unlockCondition: "于蜂窟遭遇即录入。",
    gameplayEffect: "毒针连刺多段命中，渗毒蜇刺为你叠毒、残血时额外加伤。", image: "assets/portraits/venom-bee-gu.webp",
  },
  {
    id: "enemy_beehiveBroodGu", category: "enemy", cardKey: "", enemyId: "beehiveBroodGu",
    name: "蜂巢虫蛊", alias: "蜂群孵化", rarity: "普通", faction: "毒道", type: "敌怪", stage: "蜂窟·孵母",
    descriptionShort: "背负蜂巢、越拖越凶的蜂窟孵母。",
    descriptionLore: "蜂窟录：蜂巢虫蛊背负一座蠕动的小蜂巢，每过一刻便孵出新的蜂群扑面而来。它不求速胜，只求拖久——蜂群层层叠加，越拖你越招架不住。",
    habitat: "盘踞蜂窟魔巢的孵巢深处。", feeding: "以毒蜜不断孵化新蜂群。", temperament: "慵懒孵巢，越拖蜂群越盛。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与毒蜂蛊同巢以蜂群压迫。", counteredBy: "惧高爆速杀；拖延则蜂群层数失控。",
    dropsFrom: "第三层·蜂窟魔巢 普通战。", unlockCondition: "于蜂窟遭遇即录入。",
    gameplayEffect: "持续孵化蜂群，攻击随蜂群层数累增（蜂群机制）。", image: "assets/portraits/beehive-brood-gu.webp",
  },
  {
    id: "enemy_chaosSwarmHordeGu", category: "enemy", cardKey: "", enemyId: "chaosSwarmHordeGu",
    name: "蜂潮蛊涌", alias: "密牌抢攻", rarity: "普通", faction: "毒道", type: "敌怪", stage: "蜂窟·潮群",
    descriptionShort: "裹潮成团、密牌则抢攻的蜂窟潮群。",
    descriptionLore: "蜂窟录：蜂潮蛊涌是无数毒蜂裹成的一团活潮，没有阵形、只剩乱翅。你出手越密，它越是被激得乱翅抢攻，反扑得越狠。",
    habitat: "翻涌于蜂窟魔巢的潮群通道。", feeding: "吞毒蜜噬同类残躯，越乱越盛。", temperament: "暴乱无形，受密牌激则抢攻。",
    evolution: "（生态敌怪，暂无玩家蛊牌。）", synergy: "与蜂窟守卫同巢以抢攻压迫。", counteredBy: "单回合勿出牌过密，免其抢攻反噬。",
    dropsFrom: "第三层·蜂窟魔巢 普通战。", unlockCondition: "于蜂窟遭遇即录入。",
    gameplayEffect: "你单回合出牌过密时触发抢攻，该次攻击额外加重（抢攻反噬）。", image: "assets/portraits/swarm-surge-gu.webp",
  },
  {
    id: "enemy_beehiveGuardElite", category: "enemy", cardKey: "", enemyId: "beehiveGuardElite",
    name: "蜂窟守卫", alias: "蜂刺反噬", rarity: "精英", faction: "毒道", type: "敌怪·精英", stage: "蜂窟·精英",
    descriptionShort: "披蜡甲巡巢、触之即刺的蜂窟精英。",
    descriptionLore: "蜂窟录：蜂窟守卫披着蜡甲巡弋于巢道，密集的招数会激它蜂刺反噬。它守巢极严，越是密集进攻，越被它的蜂刺扎得满身是伤。",
    habitat: "巡守蜂窟魔巢精英巢道。", feeding: "以蜡甲蜂刺截杀来犯者为养。", temperament: "森严护巢，残血则蜂刺狂涌。",
    evolution: "（蜂窟精英，暂无玩家蛊牌。）", synergy: "为灾厄蜂后护巢开道。", counteredBy: "勿密牌强攻；惧稳节奏高爆速杀。",
    dropsFrom: "第三层·蜂窟魔巢 精英战。", unlockCondition: "于蜂窟遭遇即录入。",
    gameplayEffect: "你单回合出牌过密时蜂刺反噬、攻击额外加重；蜡针连射叠毒。", image: "assets/portraits/beehive-gu-guard.webp",
  },

  /* ===== V0.9.8 第三层 · 生态条目（category:"eco"，沿用现有 eco 渲染，恒显示） ===== */
  {
    id: "eco_boneTower", category: "eco", cardKey: "",
    name: "骨塔高陵", alias: "万骨之陵", rarity: "异蛊", faction: "护身", type: "生态", stage: "生态·骨塔",
    descriptionShort: "万骨堆陵、召卫蓄力压迫的护身生态高陵。",
    descriptionLore: "生态志·骨塔：命途更深处的第三层歧路之一，万骨堆叠成陵，骨铃幽响、朽甲列阵。此径之敌高护甲、善蓄力、能召卫、多具毒抗，压力层层叠来——入此陵者须破甲打断，纯毒难速杀，方能在被骨煞镇压之前杀上塔顶。",
    habitat: "命途塔第三层 · 骨塔高陵路线全域。", feeding: "（生态环境，非可养之蛊。）", temperament: "沉寂威重，惊扰则万骨同动。",
    evolution: "（生态条目，暂无演化。）", synergy: "（生态条目，暂无战斗联动。）", counteredBy: "（生态条目。）",
    dropsFrom: "第三层骨塔路线，进入即录。", unlockCondition: "暂作生态条目展示。",
    gameplayEffect: "", image: "assets/codex/gu/bonebell-gu.webp",
  },
  {
    id: "eco_beehive", category: "eco", cardKey: "",
    name: "蜂窟魔巢", alias: "万蜂魔巢", rarity: "异蛊", faction: "毒道", type: "生态", stage: "生态·蜂窟",
    descriptionShort: "蜂群无尽、抢攻毒刺压迫的毒道生态魔巢。",
    descriptionLore: "生态志·蜂窟：命途更深处的第三层另一条歧路，毒蜜与蜂蜡织成层层巢道，蜂群无穷无尽。此径之敌善虫群孵化、抢攻反噬、毒刺多段，越拖越凶——入此巢者须控节奏、莫密攻，方能在蜂潮淹没前直捣巢心。",
    habitat: "命途塔第三层 · 蜂窟魔巢路线全域。", feeding: "（生态环境，非可养之蛊。）", temperament: "嗡鸣不息，密攻则万翅同振。",
    evolution: "（生态条目，暂无演化。）", synergy: "（生态条目，暂无战斗联动。）", counteredBy: "（生态条目。）",
    dropsFrom: "第三层蜂窟路线，进入即录。", unlockCondition: "暂作生态条目展示。",
    gameplayEffect: "", image: "assets/codex/gu/chaos-bee-gu.webp",
  },
];
