/*
 * 《逆命蛊途》万蛊录数据 · gu_catalog.js
 * 第一版只实装「蛊虫」分类；敌怪 / Boss / 异闻 / 流派 由 game.js 中的占位分类承接，
 * 以后只需往本文件追加对应 category 的条目、并在万蛊录主页放开对应 tab 即可，无需改渲染逻辑。
 *
 * 字段约定（蛊虫条目）：
 *   id              唯一编号（gu_xxx）
 *   category        固定 "gu"（蛊虫）。未来敌怪用 "enemy"、Boss 用 "boss" 等。
 *   cardKey         对应 CARD_LIBRARY 键名，用于「玩家是否曾获得」解锁判定
 *   name / alias    名称 / 别名
 *   rarity          凡蛊 / 灵蛊 / 异蛊 / 王蛊
 *   faction         毒道 / 血道 / 骨道 / 虫群 / 护身 / 燃命 / 控场 …
 *   type            攻击 / 防御 / 辅助 / 状态 / 异变
 *   stage           形态阶段（古卷口吻）
 *   descriptionShort 列表副标题用的一句话
 *   descriptionLore  古卷残篇口吻的来历异闻
 *   habitat / feeding / temperament  生态习性三联
 *   evolution / synergy / counteredBy / dropsFrom  演化·组合·克制·出处
 *   unlockCondition  解锁说明文案（展示用）
 *   gameplayEffect   战斗效果（取自卡 effect，去标签纯文本）
 *   image            立绘图路径，留空则用 glyph 单字立绘框
 */
window.GU_CATALOG = [
  {
    id: "gu_moonblade",
    category: "gu",
    cardKey: "moonBlade",
    name: "月刃蛊",
    alias: "弦月之牙",
    rarity: "凡蛊",
    faction: "护身",
    type: "攻击",
    stage: "成蛊·锋形",
    descriptionShort: "凝月华为刃的入门攻蛊。",
    descriptionLore:
      "残篇载：山月将满之夜，取蛊于古剑铭槽之内，其背生一弯白纹，状若初弦。养之七日不喂血食，唯以月光淬体，则薄翅渐硬如刃。蛊师一念既动，月刃应声而出，断敌而不沾尘。「月满则缺，刃出则收」——此乃蛊修最初学得的杀机。",
    habitat: "栖于荒祠断剑、月照所及的金石缝隙。",
    feeding: "不食血肉，唯饮月华与寒露。",
    temperament: "性冷而驯，认主极早，是蛊修第一口养器。",
    evolution: "久养可向「异刃蛊」蜕形，锋更厉而性更躁。",
    synergy: "得「酒虫」醉气加持时，一刃可断两命。",
    counteredBy: "畏厚甲与无月之夜，光弱则刃钝。",
    dropsFrom: "命途初阶、无名逆命者起手蛊囊。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "对敌人造成 6 点伤害。",
    image: "assets/codex/gu/moonblade-gu.webp",
  },
  {
    id: "gu_ironskin",
    category: "gu",
    cardKey: "ironSkin",
    name: "铁皮蛊",
    alias: "覆甲虫",
    rarity: "凡蛊",
    faction: "护身",
    type: "防御",
    stage: "成蛊·甲形",
    descriptionShort: "伏于体表化甲御伤的护蛊。",
    descriptionLore:
      "秘录残页：此蛊生于矿脉锈水之中，壳坚而色暗，似铁非铁。蛊师以气引之伏于皮下，临敌则千甲齐张、层层相叠，覆体如鳞。古谚云「铁皮一展，刀斧三分」，言其虽贱却最是耐磨的命门屏障。",
    habitat: "潜居废矿、锈水、铁器埋骨之地。",
    feeding: "啃食铁锈与金石之屑，越坚越喜。",
    temperament: "迟钝而忠，宁碎不退，护主至死。",
    evolution: "可炼为「异甲蛊」，甲更厚而反噬其主。",
    synergy: "与「残壳蛊」「蜕壳蛊」叠甲成阵，伤而愈坚。",
    counteredBy: "惧蚀甲之毒与破甲之牙，甲破则形溃。",
    dropsFrom: "命途初阶、各蛊修起手蛊囊。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 7 点防御。",
    image: "assets/codex/gu/iron-shell-gu.webp",
  },
  {
    id: "gu_wineworm",
    category: "gu",
    cardKey: "wineWorm",
    name: "酒虫",
    alias: "醉魇",
    rarity: "灵蛊",
    faction: "控场",
    type: "辅助",
    stage: "灵蛊·酿形",
    descriptionShort: "吐醉气令下一击翻倍的辅蛊。",
    descriptionLore:
      "古卷云：酒虫不入杀阵，却最坏分寸。其腹常蕴一囊浊酿，遇敌则吐雾成醉。中者神驰目眩，挥拳如缚、避刃迟半息，故继之而来的一蛊，伤可加倍。蛊师戏称：「先敬一盏，再送一刀。」",
    habitat: "藏于酒窖陈瓮、败果腐浆的甜腥之处。",
    feeding: "饮陈酿、噬醉气，越烈越肥。",
    temperament: "贪而懒，非诱以酒香不肯出囊。",
    evolution: "醉性入命，可化「醉命虫」，醉中亦能窃命。",
    synergy: "醉气加持任意攻蛊，与「月刃蛊」一刃断两命。",
    counteredBy: "对无神识、不饮不醉之傀儡尸物近乎无用。",
    dropsFrom: "命途辅助蛊奖励、燃命流起手蛊囊。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "下一张攻击蛊的伤害翻倍。",
    image: "assets/codex/gu/wineworm-gu.webp",
  },
  {
    id: "gu_bloodblade",
    category: "gu",
    cardKey: "bloodBlade",
    name: "血刃蛊",
    alias: "饮煞牙",
    rarity: "异蛊",
    faction: "血道",
    type: "攻击",
    stage: "异蛊·煞形",
    descriptionShort: "割己血换爆发、积煞愈烈的血蛊。",
    descriptionLore:
      "血道残卷：此蛊嗜主血如蜜，每出必先啮主一口，借三分热血淬其牙锋。血出愈多，煞气愈凝，凝者附于蛊背成赤纹，谓之「血煞」。煞深则一刃裂石。绛妄一脉以命饲蛊、以煞换力，正是从这一口血起。",
    habitat: "盘踞古战场尸血浸透的黑土深处。",
    feeding: "唯饮主血与战场残煞，不食他物。",
    temperament: "狂而贪，喂之愈急、索之愈狠。",
    evolution: "煞积成形可蜕「血月蛊」，月圆煞涌。",
    synergy: "与「噬心蛊」「血潮蛊」结血煞循环，越战越凶。",
    counteredBy: "惧疗血断煞之术；主血枯则蛊自噬反伤。",
    dropsFrom: "绛妄起手蛊囊、血道蛊奖励。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "失去 3 点生命，造成 13 + 当前血煞 点伤害，获得 1 层血煞。",
    image: "",
  },
  {
    id: "gu_greenmiasma",
    category: "gu",
    cardKey: "greenMiasma",
    name: "青瘴蛊",
    alias: "蟒涎瘴",
    rarity: "灵蛊",
    faction: "毒道",
    type: "状态",
    stage: "灵蛊·瘴形",
    descriptionShort: "吐青瘴叠毒、铺设蚀命之雾的毒蛊。",
    descriptionLore:
      "毒道秘篇：青瘴本是巨蟒口涎所凝，蛊师收之入囊，养以腐藤瘴气。其不咬不噬，唯吐一缕青烟附敌之身，烟不散则毒不止，层叠愈厚、蚀命愈深。青蟒一脉言：「不必一击致命，只需让它慢慢烂尽。」",
    habitat: "潜伏瘴林深泽、蟒蜕腐藤的湿绿之地。",
    feeding: "吞腐藤、噬瘴气，喜阴湿恶日光。",
    temperament: "阴而韧，不争锋而善缠，毒发无声。",
    evolution: "瘴极而变可化「异毒蛊」，一吐九层。",
    synergy: "与「虫群蛊」「腐瘴蛊」叠毒成阵，毒越深伤越重。",
    counteredBy: "惧净毒驱瘴之术与速攻爆发，毒未发已先亡。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "施加 4 层毒性。",
    image: "assets/codex/gu/green-miasma-gu.webp",
  },
  {
    id: "gu_insectswarm",
    category: "gu",
    cardKey: "insectSwarm",
    name: "虫群蛊",
    alias: "万口噬",
    rarity: "灵蛊",
    faction: "虫群",
    type: "攻击",
    stage: "灵蛊·群形",
    descriptionShort: "驱群虫啮咬、攻伤兼施毒的虫蛊。",
    descriptionLore:
      "残卷曰：一蛊为母，孵子千百，密如黑雨。临敌则倾囊而出，啮其血肉、注其毒涎，咬处溃烂、烂处复咬。蛊师御之，非以一蛊之力，而以万口之势。「单虫不足惧，万口可拆山」——此虫群之道。",
    habitat: "聚居枯木朽穴、尸骸蚁丘的密暗之所。",
    feeding: "食血肉腐殍，越腥越聚、越聚越饥。",
    temperament: "无主见而易裹挟，势成则不可遏。",
    evolution: "群密毒浓可并入「腐瘴蛊」之蚀毒循环。",
    synergy: "得「青瘴蛊」铺毒在前，群至则毒伤齐爆。",
    counteredBy: "惧火与范围净毒，一炬可焚千口。",
    dropsFrom: "青蟒流毒道蛊奖励、命途虫群事件。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 4 点伤害，并施加 4 层毒性。",
    image: "assets/codex/gu/swarm-gu.webp",
  },
  {
    id: "gu_fatethread",
    category: "gu",
    cardKey: "fateThread",
    name: "命线蛊",
    alias: "牵命丝",
    rarity: "异蛊",
    faction: "控场",
    type: "攻击",
    stage: "异蛊·命形",
    descriptionShort: "借命势加成、势盛则伤增的命蛊。",
    descriptionLore:
      "逆命残篇：此蛊体内有一缕看不见的细丝，连主之气运。蛊师攻守相替、命势渐积，丝便绷紧；势满则丝如弓弦，一拨之间割开敌命。无名逆命者无天命可恃，唯以这一线之势，自命途夹缝里硬挣出一条生路。",
    habitat: "无定所，唯附于气运纠缠、生死交错之人。",
    feeding: "不食血肉，唯汲主之「命势」而长。",
    temperament: "灵而傲，势弱则蛰伏，势盛则锋出。",
    evolution: "势数圆融，可与「定数蛊」共结命势循环。",
    synergy: "攻守交替积势，势满二层则命线一击加倍利。",
    counteredBy: "惧夺势断流之扰，命势一散则丝软无力。",
    dropsFrom: "无名逆命者起手蛊囊、命势流蛊奖励。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 8 点伤害；命势不少于 2 层时额外造成 6 点伤害。",
    image: "",
  },
  {
    id: "gu_burningessence",
    category: "gu",
    cardKey: "burningEssence",
    name: "燃元蛊",
    alias: "焚命引",
    rarity: "凡蛊",
    faction: "燃命",
    type: "辅助",
    stage: "凡蛊·火形",
    descriptionShort: "焚生命换真元、以命续力的燃蛊。",
    descriptionLore:
      "残页警语：燃元蛊小如火星，却最是凶险的捷径。它噬主一缕生机，便能在丹田点起一点真元，催动后续诸蛊。用之者快意一时，却不知每一分元气，都是从自己的命数里硬烧出来的。「燃命者，先燃己。」",
    habitat: "蛰伏炉灰余烬、丹鼎裂隙的温热之处。",
    feeding: "焚主之生机为薪，得元则旺，元尽则寒。",
    temperament: "急而烈，催之即应，不知节制。",
    evolution: "可炼入「魂燃蛊」，焚命更猛、续力更狠。",
    synergy: "为真元流起手引擎，与「聚元蛊」相济不竭。",
    counteredBy: "无外敌可克，唯主之生命为其上限，命薄则自焚。",
    dropsFrom: "燃命流起手蛊囊、命途真元事件。",
    unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 1 点真元，但失去 2 点生命。",
    image: "assets/codex/gu/burning-yuan-gu.webp",
  },
];
