/*
 * 《逆命蛊途》万蛊录数据 · gu_catalog.js
 * category="gu"  —— 已实装为战斗蛊牌(以游戏 CARD_LIBRARY 真实数据为准)，cardKey 对应卡键名、用于解锁判定。
 * category="eco" —— gu 文件夹有立绘、但游戏内暂未实装为战斗蛊牌的“生态蛊”，无 cardKey、不参与战斗，恒显示并标注“暂未实装为战斗蛊牌”。
 * 名称一律以游戏真实卡牌名为准；按“蛊虫本体”去重(每只一条)。缺图条目 image 留空，详情页回退暗色单字立绘框。
 * gameplayEffect 取自真实卡牌 effect(去标签纯文本)，不杜撰不存在的战斗效果。
 */
window.GU_CATALOG = [
  /* ===== 战斗蛊(已实装) ===== */
  {
    id: "gu_moonblade", category: "gu", cardKey: "moonBlade",
    name: "月刃蛊", alias: "弦月之牙", rarity: "凡蛊", faction: "护身", type: "攻击", stage: "成蛊·锋形",
    descriptionShort: "凝月华为刃的入门攻蛊。",
    descriptionLore: "残篇载：山月将满之夜，取蛊于古剑铭槽之内，其背生一弯白纹，状若初弦。养之七日不喂血食，唯以月光淬体，则薄翅渐硬如刃。蛊师一念既动，月刃应声而出，断敌而不沾尘。「月满则缺，刃出则收」——此乃蛊修最初学得的杀机。",
    habitat: "栖于荒祠断剑、月照所及的金石缝隙。", feeding: "不食血肉，唯饮月华与寒露。", temperament: "性冷而驯，认主极早，是蛊修第一口养器。",
    evolution: "久养可向「异刃蛊」蜕形，锋更厉而性更躁。", synergy: "得「酒虫」醉气加持时，一刃可断两命。", counteredBy: "畏厚甲与无月之夜，光弱则刃钝。",
    dropsFrom: "命途初阶、无名逆命者起手蛊囊。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "对敌人造成 6 点伤害。", image: "assets/codex/gu/moonblade-gu.webp",
  },
  {
    id: "gu_ironskin", category: "gu", cardKey: "ironSkin",
    name: "铁皮蛊", alias: "覆甲虫", rarity: "凡蛊", faction: "护身", type: "防御", stage: "成蛊·甲形",
    descriptionShort: "伏于体表化甲御伤的护蛊。",
    descriptionLore: "秘录残页：此蛊生于矿脉锈水之中，壳坚而色暗，似铁非铁。蛊师以气引之伏于皮下，临敌则千甲齐张、层层相叠，覆体如鳞。古谚云「铁皮一展，刀斧三分」，言其虽贱却最是耐磨的命门屏障。",
    habitat: "潜居废矿、锈水、铁器埋骨之地。", feeding: "啃食铁锈与金石之屑，越坚越喜。", temperament: "迟钝而忠，宁碎不退，护主至死。",
    evolution: "可炼为「异甲蛊」，甲更厚而反噬其主。", synergy: "与「残壳蛊」「蜕壳蛊」叠甲成阵，伤而愈坚。", counteredBy: "惧蚀甲之毒与破甲之牙，甲破则形溃。",
    dropsFrom: "命途初阶、各蛊修起手蛊囊。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 7 点防御。", image: "assets/codex/gu/iron-shell-gu.webp",
  },
  {
    id: "gu_wineworm", category: "gu", cardKey: "wineWorm",
    name: "酒虫", alias: "醉魇", rarity: "灵蛊", faction: "控场", type: "辅助", stage: "灵蛊·酿形",
    descriptionShort: "吐醉气令下一击翻倍的辅蛊。",
    descriptionLore: "古卷云：酒虫不入杀阵，却最坏分寸。其腹常蕴一囊浊酿，遇敌则吐雾成醉。中者神驰目眩，挥拳如缚、避刃迟半息，故继之而来的一蛊，伤可加倍。蛊师戏称：「先敬一盏，再送一刀。」",
    habitat: "藏于酒窖陈瓮、败果腐浆的甜腥之处。", feeding: "饮陈酿、噬醉气，越烈越肥。", temperament: "贪而懒，非诱以酒香不肯出囊。",
    evolution: "醉性入命，可化「醉命虫」，醉中亦能窃命。", synergy: "醉气加持任意攻蛊，与「月刃蛊」一刃断两命。", counteredBy: "对无神识、不饮不醉之傀儡尸物近乎无用。",
    dropsFrom: "命途辅助蛊奖励、燃命流起手蛊囊。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "下一张攻击蛊的伤害翻倍。", image: "assets/codex/gu/wineworm-gu.webp",
  },
  {
    id: "gu_bloodblade", category: "gu", cardKey: "bloodBlade",
    name: "血刃蛊", alias: "饮煞牙", rarity: "异蛊", faction: "血道", type: "攻击", stage: "异蛊·煞形",
    descriptionShort: "割己血换爆发、积煞愈烈的血蛊。",
    descriptionLore: "血道残卷：此蛊嗜主血如蜜，每出必先啮主一口，借三分热血淬其牙锋。血出愈多，煞气愈凝，凝者附于蛊背成赤纹，谓之「血煞」。煞深则一刃裂石。绛妄一脉以命饲蛊、以煞换力，正是从这一口血起。",
    habitat: "盘踞古战场尸血浸透的黑土深处。", feeding: "唯饮主血与战场残煞，不食他物。", temperament: "狂而贪，喂之愈急、索之愈狠。",
    evolution: "煞积成形可蜕「血月蛊」，月圆煞涌。", synergy: "与「噬心蛊」「逆血蛊」结血煞循环，越战越凶。", counteredBy: "惧疗血断煞之术；主血枯则蛊自噬反伤。",
    dropsFrom: "绛妄起手蛊囊、血道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "失去 3 点生命，造成 13 + 当前血煞 点伤害，获得 1 层血煞。", image: "",
  },
  {
    id: "gu_greenmiasma", category: "gu", cardKey: "greenMiasma",
    name: "青瘴蛊", alias: "蟒涎瘴", rarity: "灵蛊", faction: "毒道", type: "状态", stage: "灵蛊·瘴形",
    descriptionShort: "吐青瘴叠毒、铺设蚀命之雾的毒蛊。",
    descriptionLore: "毒道秘篇：青瘴本是巨蟒口涎所凝，蛊师收之入囊，养以腐藤瘴气。其不咬不噬，唯吐一缕青烟附敌之身，烟不散则毒不止，层叠愈厚、蚀命愈深。青蟒一脉言：「不必一击致命，只需让它慢慢烂尽。」",
    habitat: "潜伏瘴林深泽、蟒蜕腐藤的湿绿之地。", feeding: "吞腐藤、噬瘴气，喜阴湿恶日光。", temperament: "阴而韧，不争锋而善缠，毒发无声。",
    evolution: "瘴极而变可化「异毒蛊」，一吐九层。", synergy: "与「虫群蛊」「腐瘴蛊」叠毒成阵，毒越深伤越重。", counteredBy: "惧净毒驱瘴之术与速攻爆发，毒未发已先亡。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "施加 4 层毒性。", image: "assets/codex/gu/green-miasma-gu.webp",
  },
  {
    id: "gu_insectswarm", category: "gu", cardKey: "insectSwarm",
    name: "虫群蛊", alias: "万口噬", rarity: "灵蛊", faction: "虫群", type: "攻击", stage: "灵蛊·群形",
    descriptionShort: "驱群虫啮咬、攻伤兼施毒的虫蛊。",
    descriptionLore: "残卷曰：一蛊为母，孵子千百，密如黑雨。临敌则倾囊而出，啮其血肉、注其毒涎，咬处溃烂、烂处复咬。蛊师御之，非以一蛊之力，而以万口之势。「单虫不足惧，万口可拆山」——此虫群之道。",
    habitat: "聚居枯木朽穴、尸骸蚁丘的密暗之所。", feeding: "食血肉腐殍，越腥越聚、越聚越饥。", temperament: "无主见而易裹挟，势成则不可遏。",
    evolution: "群密毒浓可并入「腐瘴蛊」之蚀毒循环。", synergy: "得「青瘴蛊」铺毒在前，群至则毒伤齐爆。", counteredBy: "惧火与范围净毒，一炬可焚千口。",
    dropsFrom: "青蟒流毒道蛊奖励、命途虫群事件。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 4 点伤害，并施加 4 层毒性。", image: "assets/codex/gu/swarm-gu.webp",
  },
  {
    id: "gu_fatethread", category: "gu", cardKey: "fateThread",
    name: "命线蛊", alias: "牵命丝", rarity: "异蛊", faction: "控场", type: "攻击", stage: "异蛊·命形",
    descriptionShort: "借命势加成、势盛则伤增的命蛊。",
    descriptionLore: "逆命残篇：此蛊体内有一缕看不见的细丝，连主之气运。蛊师攻守相替、命势渐积，丝便绷紧；势满则丝如弓弦，一拨之间割开敌命。无名逆命者无天命可恃，唯以这一线之势，自命途夹缝里硬挣出一条生路。",
    habitat: "无定所，唯附于气运纠缠、生死交错之人。", feeding: "不食血肉，唯汲主之「命势」而长。", temperament: "灵而傲，势弱则蛰伏，势盛则锋出。",
    evolution: "势数圆融，可与「定数蛊」共结命势循环。", synergy: "攻守交替积势，与「逆途蛊」相济，势满则命线一击加倍利。", counteredBy: "惧夺势断流之扰，命势一散则丝软无力。",
    dropsFrom: "无名逆命者起手蛊囊、命势流蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 8 点伤害；命势不少于 2 层时额外造成 6 点伤害。", image: "",
  },
  {
    id: "gu_burningessence", category: "gu", cardKey: "burningEssence",
    name: "燃元蛊", alias: "焚命引", rarity: "凡蛊", faction: "燃命", type: "辅助", stage: "凡蛊·火形",
    descriptionShort: "焚生命换真元、以命续力的燃蛊。",
    descriptionLore: "残页警语：燃元蛊小如火星，却最是凶险的捷径。它噬主一缕生机，便能在丹田点起一点真元，催动后续诸蛊。用之者快意一时，却不知每一分元气，都是从自己的命数里硬烧出来的。「燃命者，先燃己。」",
    habitat: "蛰伏炉灰余烬、丹鼎裂隙的温热之处。", feeding: "焚主之生机为薪，得元则旺，元尽则寒。", temperament: "急而烈，催之即应，不知节制。",
    evolution: "可炼入「魂燃蛊」，焚命更猛、续力更狠。", synergy: "为真元流起手引擎，与「聚元蛊」相济不竭。", counteredBy: "无外敌可克，唯主之生命为其上限，命薄则自焚。",
    dropsFrom: "燃命流起手蛊囊、命途真元事件。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 1 点真元，但失去 2 点生命。", image: "assets/codex/gu/burning-yuan-gu.webp",
  },
  {
    id: "gu_hearteater", category: "gu", cardKey: "heartEater",
    name: "噬心蛊", alias: "啖心赤蛛", rarity: "异蛊", faction: "血道", type: "攻击", stage: "异蛊·赤形",
    descriptionShort: "血煞愈厚、一击啖心的重攻血蛊。",
    descriptionLore: "血道残卷：此蛊形如赤蛛，多须如根，专寻心血最盛之处下口。血煞未凝时，它只是缓缓啃咬；煞气一足，便如开闸，整颗心连血带念一并啖尽。绛妄门下传言，养此蛊者夜里常听见自己的心跳被另一物数着。（注：桌面立绘题作「蚀心蛊」，按游戏真名归为噬心蛊。）",
    habitat: "盘踞血祭遗坛、尸心未冷的暗祠。", feeding: "唯啖心血与凝结的血煞。", temperament: "贪忍而耐，越是养得久越是难填。",
    evolution: "煞极而变，可与「血月蛊」共振，月圆则啖。", synergy: "与「血刃蛊」「血祭蛊」叠煞，煞满二层则一口翻倍。", counteredBy: "煞气一断便绵软无力；惧疗血与净煞之术。",
    dropsFrom: "通用进阶牌池(战后奖励)、血道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 12 点伤害；血煞不少于 2 层时改为 20。", image: "assets/codex/gu/heart-eater-gu.webp",
  },
  {
    id: "gu_bloodreversal", category: "gu", cardKey: "bloodReversal",
    name: "逆血蛊", alias: "倒煞牙", rarity: "异蛊", faction: "血道", type: "攻击", stage: "异蛊·逆形",
    descriptionShort: "倾血逆冲、煞重则爆发翻涌的血蛊。",
    descriptionLore: "血道秘篇：寻常血蛊顺血而行，此蛊偏要倒着来。它咬开主脉，令血不外流而内逆，逼出沉积的旧煞一并外放。代价是元气大伤，所得却是煞气倍涌、一击如崩堤。绛妄说：「敢用逆血者，是把命押在下一刀上。」",
    habitat: "生于血脉逆乱、横死不甘者的残骸。", feeding: "饮逆流之血与翻涌的旧煞。", temperament: "暴烈难驯，喂则索更多，稍纵即反噬。",
    evolution: "逆煞难收，常自行崩解或并入更凶的血道异蛊。", synergy: "与「血刃蛊」「噬心蛊」同囊，煞越厚逆血越猛。", counteredBy: "极耗主血，连出则力竭；惧疗血与速决。",
    dropsFrom: "通用进阶牌池(战后奖励)、血道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "失去 5 点生命，造成 16 + 血煞×2 点伤害，获得 1 层血煞。", image: "",
  },
  {
    id: "gu_shellremnant", category: "gu", cardKey: "shellRemnant",
    name: "残壳蛊", alias: "弃甲虫", rarity: "灵蛊", faction: "护身", type: "防御", stage: "灵蛊·残形",
    descriptionShort: "受创愈坚、以残壳叠甲的护蛊。",
    descriptionLore: "护身残页：此蛊以蜕下的旧壳为食，越是破碎的甲它越啃得欢。临敌时但凡主受一击，它便急急取残壳补缀，伤口一开、甲反更厚。蛊师笑称：「它是越打越精神的犟脾气。」",
    habitat: "栖于蜕壳堆、败甲废铠的残骸之间。", feeding: "啃食破碎旧甲与蜕壳。", temperament: "倔而韧，受激则盛，安逸则懒。",
    evolution: "可炼为「蜕甲蛊」，弃旧迎新、甲随蜕生。", synergy: "与「铁皮蛊」「蜕壳蛊」叠甲，受创循环愈厚。", counteredBy: "未受创时所得有限；惧蚀甲与破甲连击。",
    dropsFrom: "通用构筑牌(奖励与蛊坊)。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 6 点防御；若本回合已受伤，额外获得 6 点防御。", image: "",
  },
  {
    id: "gu_reversepath", category: "gu", cardKey: "reversePath",
    name: "逆途蛊", alias: "踏命引", rarity: "灵蛊", faction: "控场", type: "辅助", stage: "灵蛊·途形",
    descriptionShort: "零耗积势、攻守相替的命势辅蛊。",
    descriptionLore: "逆命残篇：天命之人顺途而行，无名逆命者却只能逆途夺命。此蛊不耗真元，只在主每一次攻守转换间，悄悄替他攒下一分命势、一缕护气。途虽逆，步步皆数。「顺者天与，逆者自取。」",
    habitat: "无定所，附于不肯认命、屡败屡起之人。", feeding: "不食血肉，汲主攻守交替间漏出的命势。", temperament: "沉静而执，势弱不弃，步步为营。",
    evolution: "势数纯熟可与「断命蛊」「定数蛊」共结命势环。", synergy: "与「命线蛊」相济：先以逆途积势，再以命线收割。", counteredBy: "本身无伤无防峰值，惧被速攻打断节奏。",
    dropsFrom: "无名逆命者起手蛊囊、命势流蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 3 点防御，并获得 1 层命势。", image: "",
  },
  {
    id: "gu_moltingshell", category: "gu", cardKey: "moltingShell",
    name: "蜕壳蛊", alias: "褪甲蜕", rarity: "灵蛊", faction: "毒道", type: "防御", stage: "灵蛊·蜕形",
    descriptionShort: "御伤兼借毒生机的毒道护蛊。",
    descriptionLore: "毒道杂篇：此蛊半毒半甲，蜕壳之际既能护体，又能从敌身的毒里汲一线生机。青蟒一脉以毒铺路、以蜕壳守身，毒越深，它退得越从容。「敌中我毒，我便从它的烂处取一口活路。」",
    habitat: "潜居瘴泽蜕壳、毒藤盘结之处。", feeding: "食蜕壳，亦从中毒之敌身上汲毒为养。", temperament: "阴而稳，善守善退，不喜强攻。",
    evolution: "可与「腐瘴蛊」共生，蜕中带毒、守中藏蚀。", synergy: "与「青瘴蛊」「虫群蛊」铺毒在前，蜕壳愈从容。", counteredBy: "敌不中毒时只是寻常护甲；惧破甲与净毒。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "获得 8 点防御；若敌人已中毒，抽 1 张牌。", image: "",
  },
  {
    id: "gu_poisonreturn", category: "gu", cardKey: "poisonReturn",
    name: "返毒蛊", alias: "蝎返瘴", rarity: "灵蛊", faction: "毒道", type: "攻击", stage: "灵蛊·蝎形",
    descriptionShort: "毒深则反噬、借敌之毒重击的毒蛊。",
    descriptionLore: "毒道残卷：此蛊形如毒蝎，尾悬一囊浊瘴。寻常一蜇不过小伤，可一旦敌身积毒已深，它便将那毒尽数勾出、连本带利返还其身。青蟒门人最爱在敌烂透时唤它收尾——「你欠下的毒，该连利还了。」",
    habitat: "盘踞毒潭蝎窟、瘴气最浓的死水边。", feeding: "噬瘴气与中毒之物，毒越浓越肥。", temperament: "蛰伏耐等，毒不深不动，一动即收命。",
    evolution: "瘴极可向毒道异蛊蜕形，一返九层。", synergy: "与「青瘴蛊」「腐瘴蛊」「虫群蛊」叠毒在前，返毒爆发倍增。", counteredBy: "敌毒浅时威胁有限；惧净毒断瘴与速攻。",
    dropsFrom: "青蟒起手蛊囊、毒道蛊奖励。", unlockCondition: "蛊囊中曾收容此蛊即录入。",
    gameplayEffect: "造成 6 点伤害；若敌人中毒不少于 8 层，额外造成 8 点伤害。", image: "assets/codex/gu/return-poison-gu.webp",
  },

  /* ===== 生态蛊(gu 文件夹有立绘、游戏内暂未实装为战斗蛊牌) ===== */
  {
    id: "eco_bonebell", category: "eco", cardKey: "",
    name: "骨铃蛊", alias: "招魂铃", rarity: "异蛊", faction: "骨道", type: "生态", stage: "异蛊·骨形",
    descriptionShort: "颅骨悬铃、铃响则魂动的骨道异蛊。",
    descriptionLore: "骨道异闻：枯井深处常拾得一串骨铃，乃此蛊蜕下的躯壳。活蛊以颅骨为腹、以骨刺为足，行动时铃声幽幽，凡闻者皆觉有人在背后数自己尚余几年寿。世人讳称它「招魂的更夫」。",
    habitat: "盘踞枯井、乱葬、断碑之下的骨堆。", feeding: "啃食陈骨与残念，铃声越密食得越欢。", temperament: "阴冷好静，受惊则铃乱、骨刺尽张。",
    evolution: "（未实装，演化路线待考。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备，游戏内尚无对应蛊牌。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/bonebell-gu.webp",
  },
  {
    id: "eco_chaosbee", category: "eco", cardKey: "",
    name: "乱蜂蛊", alias: "千刺潮", rarity: "灵蛊", faction: "虫群", type: "生态", stage: "灵蛊·蜂形",
    descriptionShort: "群刺如雨、红目凶悍的虫群生态蛊。",
    descriptionLore: "虫群杂记：此蜂不结一巢，而以蛊母为心、聚潮成阵。怒时尾刺如雨倾射，金纹赤目，所过之处寸草溃烂。命途中所遇之「乱蜂蛊潮」，便是此蛊成势之相。养之为牌者尚未现世。",
    habitat: "聚居断崖蜂岩、腐花毒蜜之地。", feeding: "采毒花、噬腐蜜，亦食同类残躯。", temperament: "暴躁群涌，一激则倾巢，难独驯。",
    evolution: "（未实装；其成潮之相见敌怪「乱蜂蛊潮」。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备；游戏内现以敌怪「乱蜂蛊潮」登场，尚无玩家蛊牌。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/chaos-bee-gu.webp",
  },
  {
    id: "eco_snakeshell", category: "eco", cardKey: "",
    name: "蛇壳蛊", alias: "鳞缠盘", rarity: "灵蛊", faction: "毒道", type: "生态", stage: "灵蛊·蛇形",
    descriptionShort: "鳞甲缠身、盘踞御毒的蛇形生态蛊。",
    descriptionLore: "毒道异闻：此蛊托身于蜕下的巨蛇之壳，鳞片层叠如甲，盘绕一团便是一座活的毒障。它不主动伤人，只把自己缠成铜墙，逼来犯者先碰一身鳞毒。立绘题作「毒道·防御蛊」，惜游戏内尚未成牌。",
    habitat: "栖于蛇蜕岩窟、毒藤盘结的湿暗深处。", feeding: "吞蛇蜕与鳞间积毒，喜阴恶光。", temperament: "沉静自守，非犯不动，一动则缠死。",
    evolution: "（未实装，防御演化路线待考。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备，游戏内尚无对应蛊牌(注：游戏另有「蜕壳蛊」，非同一只)。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/snake-shell-gu.webp",
  },
  {
    id: "eco_bloodmarsh", category: "eco", cardKey: "",
    name: "血沼蛊", alias: "沉血蚿", rarity: "异蛊", faction: "血道", type: "生态", stage: "异蛊·沼形",
    descriptionShort: "粗躯倒刺、生于血沼深处的血道生态蛊。",
    descriptionLore: "百血录·异闻：生于血沼深渊，躯粗如管、满覆倒刺，吸血而肥、沉血而眠。它不挑食，过路的活物、沉底的旧血、连同沼里未散的怨气，都一并吞下。立绘题「百血录·血道类」，凶名在外，惜游戏内暂未成牌。",
    habitat: "沉眠血沼、尸血淤积的深渊底泥。", feeding: "吸活血、吞旧血，越腥越沉越肥。", temperament: "迟缓而贪，醒则吞噬一切，难近难驯。",
    evolution: "（未实装，血道演化路线待考。）", synergy: "（未实装，暂无战斗联动。）", counteredBy: "（未实装。）",
    dropsFrom: "桌面立绘已备，游戏内尚无对应蛊牌(近似的有血潮蛊/血月蛊，非同一只)。", unlockCondition: "暂未实装为战斗蛊牌。",
    gameplayEffect: "", image: "assets/codex/gu/bloodmarsh-gu.webp",
  },
];
